### ISSUE TITLE
how to avoid false detection of people fall to sit on ground?

### ISSUE THREAD

**Issue by yunfan** [harishrithish7/Fall-Detection#1]
is it by speed or other ?

**Comment by harishrithish7** [comment]
There are 2 things to differentiate falling and sitting.
1. As you mentioned,  **Speed**. If one were to sit down normally, the speed associated would be much lower than that of falling down unintentionally. However, if someone were to sit down with high velocity, then the 2nd criteria, mentioned below, comes into play.
2. **Orientation change**. When a person falls down, he moves from a vertical orientation (standing position) to a horizontal orientation (sleeping position) in a short duration of time. This however is not the case when a person sits down as there is only a slight variation in the orientation change.

Have a look at the demo for a better idea.  [https://www.youtube.com/watch?v=LdoLniUSOaA]

**Comment by yunfan** [comment]
ok thanks for the explaining.
then how much computing of such detection will require? i was wondering if SBCs like RPI could support such computing?
